# Generated by Django 5.2.7 on 2025-10-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_initial"),
        ("emails", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcredentials",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_credentials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="credentials",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="emails.emailcredentials",
                verbose_name="credentials",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="related_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_emails",
                to="companies.company",
                verbose_name="related company",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_emails",
                to="projects.project",
                verbose_name="related project",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="emails.emailmessage",
                verbose_name="email",
            ),
        ),
        migrations.AddField(
            model_name="emailprocessingrule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_rules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="emailsynclog",
            name="credentials",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="emails.emailcredentials",
                verbose_name="credentials",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["user", "-received_at"], name="emails_emai_user_id_6c91cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["credentials", "-received_at"],
                name="emails_emai_credent_1ed629_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["message_id"], name="emails_emai_message_e07b6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(fields=["sender"], name="emails_emai_sender_6dca79_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["parsed_inn"], name="emails_emai_parsed__b9af2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["parsed_project_number"], name="emails_emai_parsed__ea3262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["is_processed"], name="emails_emai_is_proc_a57b15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["related_company"], name="emails_emai_related_82dae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["related_project"], name="emails_emai_related_a714bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["email", "is_downloaded"], name="emails_emai_email_i_6a873d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["content_type"], name="emails_emai_content_ccfbcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["is_inline"], name="emails_emai_is_inli_d8c4e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailprocessingrule",
            index=models.Index(
                fields=["user", "priority"], name="emails_emai_user_id_35dacb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailprocessingrule",
            index=models.Index(
                fields=["user", "is_active"], name="emails_emai_user_id_800a9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsynclog",
            index=models.Index(
                fields=["credentials", "-started_at"],
                name="emails_emai_credent_e921bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailsynclog",
            index=models.Index(fields=["status"], name="emails_emai_status_ea4fe0_idx"),
        ),
    ]
