# Generated by Django 5.2.7 on 2025-10-29 10:48

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="company"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="position"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="whatsapp"
                    ),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="linkedin")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="favorite"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="color"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "contact group",
                "verbose_name_plural": "contact groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                ("file_format", models.CharField(max_length=10, verbose_name="format")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "total_contacts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total contacts"
                    ),
                ),
                (
                    "imported_contacts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="imported contacts"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="errors"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "contact import",
                "verbose_name_plural": "contact imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("note", "Note"),
                            ("task", "Task"),
                            ("other", "Other"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="date")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duration (minutes)"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="outcome"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "contact interaction",
                "verbose_name_plural": "contact interactions",
                "ordering": ["-date"],
            },
        ),
    ]
