# Generated by Django 5.2.7 on 2025-10-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="contactgroup",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                to="contacts.contact",
                verbose_name="contacts",
            ),
        ),
        migrations.AddField(
            model_name="contactgroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="contactimport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="contactinteraction",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="contacts.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AddField(
            model_name="contactinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_interactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "email"], name="contacts_co_user_id_c01fd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "phone"], name="contacts_co_user_id_f3ce01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "first_name", "last_name"],
                name="contacts_co_user_id_6a2cb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "company"], name="contacts_co_user_id_745888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "is_favorite"], name="contacts_co_user_id_0bcb89_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactgroup",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="contactinteraction",
            index=models.Index(
                fields=["contact", "-date"], name="contacts_co_contact_678cc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactinteraction",
            index=models.Index(
                fields=["user", "-date"], name="contacts_co_user_id_2244a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactinteraction",
            index=models.Index(
                fields=["interaction_type", "-date"],
                name="contacts_co_interac_1a7546_idx",
            ),
        ),
    ]
