# Generated by Django 5.2.7 on 2025-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="phone verified"),
        ),
    ]
