# Generated by Django 5.2.7 on 2025-10-29 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="content type"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="size (bytes)")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="file path"),
                ),
                (
                    "is_downloaded",
                    models.BooleanField(default=False, verbose_name="downloaded"),
                ),
                (
                    "download_errors",
                    models.TextField(blank=True, verbose_name="download errors"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "project attachment",
                "verbose_name_plural": "project attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="message id"
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="subject")),
                ("sender", models.EmailField(max_length=254, verbose_name="sender")),
                (
                    "recipients",
                    models.JSONField(default=list, verbose_name="recipients"),
                ),
                ("body", models.TextField(verbose_name="body")),
                ("received_at", models.DateTimeField(verbose_name="received at")),
                (
                    "has_attachments",
                    models.BooleanField(default=False, verbose_name="has attachments"),
                ),
                (
                    "attachments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="attachments count"
                    ),
                ),
                (
                    "parsed_inn",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="parsed ИНН"
                    ),
                ),
                (
                    "parsed_project_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="parsed project number"
                    ),
                ),
                (
                    "parsed_contacts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="parsed contacts"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="processed"),
                ),
                (
                    "processing_errors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="processing errors"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "project email",
                "verbose_name_plural": "project emails",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("meeting", "Meeting"),
                            ("call", "Call"),
                            ("decision", "Decision"),
                            ("issue", "Issue"),
                            ("solution", "Solution"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="note type",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="important"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="private"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "project note",
                "verbose_name_plural": "project notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="old status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="new status",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="changed at"),
                ),
            ],
            options={
                "verbose_name": "project status history",
                "verbose_name_plural": "project status history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        help_text="ИНН из email",
                        max_length=12,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        blank=True,
                        help_text="Номер проекта из email",
                        max_length=50,
                        verbose_name="project number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="deadline"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "source_email_id",
                    models.CharField(
                        blank=True,
                        help_text="ID email из которого создан проект",
                        max_length=255,
                        verbose_name="source email id",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
