# Generated by Django 5.2.7 on 2025-10-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="projectemail",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AddField(
            model_name="projectattachment",
            name="project_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="projects.projectemail",
                verbose_name="project email",
            ),
        ),
        migrations.AddField(
            model_name="projectnote",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_notes",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AddField(
            model_name="projectnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="projectstatushistory",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AddField(
            model_name="projectstatushistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_status_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "status"], name="projects_pr_user_id_40c3f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "priority"], name="projects_pr_user_id_d72d56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "inn"], name="projects_pr_user_id_8820eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "project_number"], name="projects_pr_user_id_a743dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "created_at"], name="projects_pr_user_id_29bec8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "deadline"], name="projects_pr_user_id_d39c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["company", "status"], name="projects_pr_company_48dbe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["contact", "status"], name="projects_pr_contact_52d882_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectemail",
            index=models.Index(
                fields=["project", "-received_at"],
                name="projects_pr_project_6f3be4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectemail",
            index=models.Index(
                fields=["message_id"], name="projects_pr_message_1d7db2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectemail",
            index=models.Index(fields=["sender"], name="projects_pr_sender_cac059_idx"),
        ),
        migrations.AddIndex(
            model_name="projectemail",
            index=models.Index(
                fields=["parsed_inn"], name="projects_pr_parsed__514d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectemail",
            index=models.Index(
                fields=["parsed_project_number"], name="projects_pr_parsed__35135f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectemail",
            index=models.Index(
                fields=["is_processed"], name="projects_pr_is_proc_b38c31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectattachment",
            index=models.Index(
                fields=["project_email", "is_downloaded"],
                name="projects_pr_project_ecd705_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectattachment",
            index=models.Index(
                fields=["content_type"], name="projects_pr_content_c5a063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectnote",
            index=models.Index(
                fields=["project", "is_important"],
                name="projects_pr_project_c68530_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectnote",
            index=models.Index(
                fields=["project", "note_type"], name="projects_pr_project_d0541e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectnote",
            index=models.Index(
                fields=["user", "created_at"], name="projects_pr_user_id_784877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectnote",
            index=models.Index(
                fields=["project", "is_private"], name="projects_pr_project_aae24a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectstatushistory",
            index=models.Index(
                fields=["project", "-changed_at"], name="projects_pr_project_4ad4bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectstatushistory",
            index=models.Index(
                fields=["user", "-changed_at"], name="projects_pr_user_id_84f4c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectstatushistory",
            index=models.Index(
                fields=["old_status", "new_status"],
                name="projects_pr_old_sta_b43646_idx",
            ),
        ),
    ]
