# Generated by Django 5.2.7 on 2025-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="inn",
            field=models.CharField(
                blank=True,
                help_text="ИНН из email",
                max_length=12,
                null=True,
                verbose_name="ИНН",
            ),
        ),
    ]
