# Generated by Django 5.2.7 on 2025-10-29 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "inn",
                    models.CharField(
                        help_text="10 or 12 digits",
                        max_length=12,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                ("legal_address", models.TextField(verbose_name="legal address")),
                (
                    "actual_address",
                    models.TextField(blank=True, verbose_name="actual address"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact person"
                    ),
                ),
                (
                    "contact_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact position"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="in rubles",
                        max_digits=12,
                        verbose_name="credit limit",
                    ),
                ),
                (
                    "current_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="in rubles",
                        max_digits=12,
                        verbose_name="current debt",
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("supplier", "Supplier"),
                            ("partner", "Partner"),
                            ("competitor", "Competitor"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="company type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("meeting", "Meeting"),
                            ("call", "Call"),
                            ("negotiation", "Negotiation"),
                            ("complaint", "Complaint"),
                            ("praise", "Praise"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="note type",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="important"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "company note",
                "verbose_name_plural": "company notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="order number"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="in rubles",
                        max_digits=12,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(auto_now_add=True, verbose_name="order date"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="completion date"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="in rubles",
                        max_digits=12,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="payment number"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="invoice number"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="payment date")),
                (
                    "received_date",
                    models.DateField(auto_now_add=True, verbose_name="received date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-payment_date"],
            },
        ),
    ]
