# Generated by Django 5.2.7 on 2025-10-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="companynote",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_notes",
                to="companies.company",
                verbose_name="company",
            ),
        ),
        migrations.AddField(
            model_name="companynote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="companies.company",
                verbose_name="company",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="companies.company",
                verbose_name="company",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="companies.order",
                verbose_name="order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["user", "inn"], name="companies_c_user_id_ed9a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["user", "name"], name="companies_c_user_id_437c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["user", "company_type"], name="companies_c_user_id_83c51c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["user", "status"], name="companies_c_user_id_406f3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["user", "is_active"], name="companies_c_user_id_00a4ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("user", "inn")},
        ),
        migrations.AddIndex(
            model_name="companynote",
            index=models.Index(
                fields=["company", "is_important"],
                name="companies_c_company_1b1182_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companynote",
            index=models.Index(
                fields=["user", "created_at"], name="companies_c_user_id_9707bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companynote",
            index=models.Index(
                fields=["note_type"], name="companies_c_note_ty_f5f17f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["company", "status"], name="companies_o_company_9c777f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="companies_o_user_id_d442f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="companies_o_order_n_1619ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_date"], name="companies_o_order_d_b5eed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["due_date"], name="companies_o_due_dat_83a01d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("company", "order_number")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["company", "status"], name="companies_p_company_519ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="companies_p_order_i_f3bea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="companies_p_user_id_c305bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="companies_p_payment_53d768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["received_date"], name="companies_p_receive_1af140_idx"
            ),
        ),
    ]
