# Generated by Django 5.2.7 on 2025-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="inn",
            field=models.CharField(
                help_text="10 or 12 digits",
                max_length=12,
                null=True,
                unique=True,
                verbose_name="ИНН",
            ),
        ),
    ]
