name: Code Audit & Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync
        uv install

    - name: Run linters (flake8, mypy, black check)
      run: |
        uv run flake8 .
        uv run mypy .
        # uv run black --check .
        uv run black --check --diff .

    - name: Run tests with coverage
      run: uv run pytest --cov=.

    - name: Run Security scan (bandit)
      run: |
        pip install bandit
        bandit -r .

  ai_code_review:
    needs: lint_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: AI Code Review (GitHub Marketplace Action example)
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security-and-quality'
