name: AI Code Review

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ai-code-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh   # astral-sh/setup-uv@v4
        uv sync --dev             # uv install

    - name: Run linters (ruff, mypy, black check)
      run: |
        uv run ruff check .           # Проверка линтинга
        uv run mypy crm
        uv run black --check --diff .  # uv run black --check .

    # - name: Run tests with coverage
    #   run: uv run pytest --cov=.

    # - name: Run Security scan (bandit)
    #   run: |
    #     pip install bandit
    #     bandit -r .

    - name: AI Code Reviewer
      # uses: fletch4503/ai-code-reviewer@master
      uses: coderabbitai/ai-pr-reviewer@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
        exclude: "**/*.json,**/*.md" # Optional: exclude patterns separated by commas