name: Code Audit & Quality Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh   # astral-sh/setup-uv@v4
        uv sync --dev             # uv install

    - name: Run linters (ruff, mypy, black check)
      run: |
        uv run ruff check .           # Проверка линтинга
        uv run mypy crm
        uv run black --check --diff .  # uv run black --check .

    - name: Run tests with coverage
      run: uv run pytest --cov=.

    - name: Run Security scan (bandit)
      run: |
        pip install bandit
        bandit -r .

  ai_code_review:
    needs: lint_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: AI Code Review (GitHub Marketplace Action example)
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security-and-quality'
